// Beweisarten. key = interner Schlüssel, short = Kurzlabel, name = volle Bezeichnung, svg = Vektor-Icon.
const ICONS = {
  // EMF-Reader im K-II-Stil: dunkles Gerät mit LED-Fächer (grün→rot)
  emf: `<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><rect x="7" y="2.5" width="10" height="19" rx="1.8" fill="#1f2229" stroke="#5b6472" stroke-width="1"/><circle cx="9" cy="7.2" r="1.05" fill="#3ecf7a"/><circle cx="10.5" cy="5.7" r="1.05" fill="#3ecf7a"/><circle cx="12" cy="5.1" r="1.05" fill="#ffd23e"/><circle cx="13.5" cy="5.7" r="1.05" fill="#ff9a3e"/><circle cx="15" cy="7.2" r="1.05" fill="#ff5d6c"/><rect x="9" y="11" width="6" height="1.4" rx="0.7" fill="#3a4150"/><circle cx="12" cy="16.6" r="2.1" fill="#2b2f3a" stroke="#5b6472" stroke-width="0.8"/><circle cx="12" cy="16.6" r="0.8" fill="#5b6472"/></svg>`,
  // Spirit Box: schwarzes Handscanner-Gerät mit grünem Display, Antenne und Tasten
  spiritbox: `<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><line x1="6.5" y1="6" x2="4" y2="2.8" stroke="#9aa3b2" stroke-width="1.2" stroke-linecap="round"/><circle cx="3.8" cy="2.6" r="0.9" fill="#9aa3b2"/><rect x="5" y="5.5" width="14" height="14" rx="2" fill="#181b21" stroke="#5b6472" stroke-width="1"/><rect x="7" y="7.3" width="10" height="4.4" rx="0.8" fill="#0c1a12"/><rect x="7.8" y="9.1" width="8" height="0.9" rx="0.45" fill="#3ecf7a"/><g fill="#4a525f"><rect x="7" y="13.4" width="2.9" height="1.9" rx="0.5"/><rect x="10.55" y="13.4" width="2.9" height="1.9" rx="0.5"/><rect x="14.1" y="13.4" width="2.9" height="1.9" rx="0.5"/><rect x="7" y="16.1" width="2.9" height="1.9" rx="0.5"/><rect x="10.55" y="16.1" width="2.9" height="1.9" rx="0.5"/><rect x="14.1" y="16.1" width="2.9" height="1.9" rx="0.5"/></g></svg>`,
  // UV: Fingerabdruck in UV-Lila
  uv: `<svg viewBox="0 0 24 24" fill="none" stroke="#b894ff" stroke-width="1.2" stroke-linecap="round" xmlns="http://www.w3.org/2000/svg"><path d="M12 4.4c-4.2 0-7.2 3-7.2 6.9 0 1.8.4 3.6 1.1 5"/><path d="M12 7.5c-2.6 0-4.3 1.9-4.3 4.1 0 1.7.3 3.4.9 4.9"/><path d="M12 10.6c-1.2 0-1.9.9-1.9 2.1 0 1.7.4 3.4 1.2 4.9"/><path d="M14.9 6c1.7 1.3 2.7 3.1 2.7 5.3 0 2.2-.2 4.3-.9 6.3"/><path d="M14.7 12c0 2.3-.2 4.5-.9 6.5"/></svg>`,
  // Geisterkugel: leuchtende Kugel mit Halo
  orbs: `<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="12" r="10" fill="#7fc7ff" opacity="0.16"/><circle cx="12" cy="12" r="6.4" fill="#b4e2ff"/><circle cx="12" cy="12" r="6.4" fill="none" stroke="#5aa8d6" stroke-width="0.8"/><circle cx="9.9" cy="9.9" r="1.7" fill="#ffffff" opacity="0.85"/></svg>`,
  // Geisterschrift: braunes, aufgeschlagenes Geisterbuch mit Zeilen
  writing: `<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 6.2C9.8 4.6 6.5 4.4 3.5 5.2v13c3-.8 6.3-.6 8.5 1 2.2-1.6 5.5-1.8 8.5-1v-13c-3-.8-6.3-.6-8.5 1z" fill="#caa46a" stroke="#6b4a2b" stroke-width="1.2" stroke-linejoin="round"/><path d="M12 6.2v12.9" stroke="#6b4a2b" stroke-width="1.1"/><g stroke="#6b4a2b" stroke-width="0.8" stroke-linecap="round" opacity="0.85"><line x1="5.2" y1="8" x2="10" y2="8.6"/><line x1="5.2" y1="10.2" x2="10" y2="10.8"/><line x1="5.2" y1="12.4" x2="10" y2="13"/><line x1="14" y1="8.6" x2="18.8" y2="8"/><line x1="14" y1="10.8" x2="18.8" y2="10.2"/><line x1="14" y1="13" x2="18.8" y2="12.4"/></g></svg>`,
  // Gefriertemperaturen: Schneeflocke
  freezing: `<svg viewBox="0 0 24 24" fill="none" stroke="#8fd8ff" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" xmlns="http://www.w3.org/2000/svg"><line x1="12" y1="2.5" x2="12" y2="21.5"/><line x1="3.8" y1="7.25" x2="20.2" y2="16.75"/><line x1="20.2" y1="7.25" x2="3.8" y2="16.75"/><path d="M12 2.5l-2 2M12 2.5l2 2M12 21.5l-2-2M12 21.5l2-2"/><path d="M3.8 7.25l.3 2.7M3.8 7.25l2.7-.3M20.2 16.75l-.3-2.7M20.2 16.75l-2.7.3"/><path d="M20.2 7.25l-2.7-.3M20.2 7.25l-.3 2.7M3.8 16.75l2.7.3M3.8 16.75l.3-2.7"/></svg>`,
  // D.O.T.S.: Raster aus vielen grünen Punkten
  dots: `<svg viewBox="0 0 24 24" fill="#3ecf7a" xmlns="http://www.w3.org/2000/svg"><circle cx="4" cy="4" r="1.15"/><circle cx="9.5" cy="4" r="1.15"/><circle cx="15" cy="4" r="1.15"/><circle cx="20.5" cy="4" r="1.15"/><circle cx="4" cy="9.5" r="1.15"/><circle cx="9.5" cy="9.5" r="1.15"/><circle cx="15" cy="9.5" r="1.15"/><circle cx="20.5" cy="9.5" r="1.15"/><circle cx="4" cy="15" r="1.15"/><circle cx="9.5" cy="15" r="1.15"/><circle cx="15" cy="15" r="1.15"/><circle cx="20.5" cy="15" r="1.15"/><circle cx="4" cy="20.5" r="1.15"/><circle cx="9.5" cy="20.5" r="1.15"/><circle cx="15" cy="20.5" r="1.15"/><circle cx="20.5" cy="20.5" r="1.15"/></svg>`,
};

// Typische Contract-Ziele. Manuell abhakbar; optional = zufälliges Vertragsziel
// (nur diese sollen angezeigt werden, wenn das Journal aus dem Spiel gelesen wird).
// aliases = Kleinschreib-Teilstrings (DE/EN) zum Matchen der ausgelesenen Journal-Texte.
const OBJECTIVES = [
  { key: 'identify',    label: 'Geist identifizieren',     optional: false, aliases: ['identif', 'geist identi', 'type of ghost', 'art des geist'] },
  { key: 'photo',       label: 'Geist fotografieren',      optional: true,  aliases: ['foto', 'photo', 'picture of the ghost'] },
  { key: 'emf_event',   label: 'EMF Level 5 (Event)',      optional: true,  aliases: ['emf'] },
  { key: 'ghost_event', label: 'Geister-Event (Video)',    optional: true,  aliases: ['ghost event', 'geister-event', 'geisterereignis', 'witness a ghost'] },
  { key: 'dots_sil',    label: 'DOTS-Silhouette',          optional: true,  aliases: ['dots', 'd.o.t.s'] },
  { key: 'crucifix',    label: 'Jagd mit Kruzifix stoppen', optional: true, aliases: ['kruzifix', 'crucifix'] },
  { key: 'smudge',      label: 'Geist mit Räucherwerk',    optional: true,  aliases: ['räucher', 'raeucher', 'smudge', 'cleanse'] },
  { key: 'salt',        label: 'Salz getriggert',          optional: true,  aliases: ['salz', 'salt'] },
];

const EVIDENCE = [
  // png wird automatisch verwendet, sobald die Datei existiert – sonst Fallback auf svg.
  { key: 'emf',       short: 'EMF',     name: 'EMF Level 5',                    svg: ICONS.emf,       png: 'icons/emf.png' },
  { key: 'spiritbox', short: 'Box',     name: 'Spirit Box',                     svg: ICONS.spiritbox, png: 'icons/spiritbox.png' },
  { key: 'uv',        short: 'UV',      name: 'Ultraviolett (Fingerabdrücke)',  svg: ICONS.uv },
  { key: 'orbs',      short: 'Orbs',    name: 'Geisterkugeln (Orbs)',           svg: ICONS.orbs },
  { key: 'writing',   short: 'Buch',    name: 'Geisterschrift',                 svg: ICONS.writing },
  { key: 'freezing',  short: 'Kälte',   name: 'Gefriertemperaturen',            svg: ICONS.freezing },
  { key: 'dots',      short: 'DOTS',    name: 'D.O.T.S. Projektor',             svg: ICONS.dots },
];

// Normale Geschwindigkeit = 1.7 m/s, normale Jagd-Schwelle = 50% Sanity.
// orbsAlways: Mimic zeigt Kugeln immer als 4. (Fake-)Beweis.
const GHOSTS = [
  {
    name: 'Spirit',
    evidence: ['emf', 'spiritbox', 'writing'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Keine besondere aktive Fähigkeit.',
    strength: 'Keine ausnutzbare Stärke.',
    weakness: 'Räucherwerk (Smudge) verhindert die Jagd 180 s lang statt 90 s.',
    behaviors: ['Sehr „gewöhnlicher" Geist ohne auffälliges Sonderverhalten.'],
    tip: 'Smudge zünden: jagt es danach ungewöhnlich lange nicht (180 s) → Spirit.',
  },
  {
    name: 'Wraith',
    evidence: ['emf', 'spiritbox', 'dots'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Kann sich teleportieren – auch direkt zu einem Spieler (danach EMF an der Stelle).',
    strength: 'Hinterlässt nach dem Teleport keine Spur und schwebt (keine Salz-Fußspuren).',
    weakness: 'Tritt nicht in Salz – läuft nicht hinein und hinterlässt keine UV-Fußabdrücke im Salz.',
    behaviors: [
      'Berührt niemals Salz.',
      'Teleportiert sich gelegentlich quer durch die Karte.',
    ],
    tip: 'Salz auslegen + UV: keine Fußspuren im/nach dem Salz → Wraith.',
  },
  {
    name: 'Phantom',
    evidence: ['spiritbox', 'uv', 'dots'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Es direkt anzusehen senkt die Sanity schneller als bei anderen Geistern.',
    strength: 'Während der Jagd seltener sichtbar (blinkt langsamer, lange unsichtbar).',
    weakness: 'Ein Foto während der Jagd lässt es kurz verschwinden.',
    behaviors: [
      'In der Jagd nur kurz und selten sichtbar.',
      'Anstarren zieht zusätzlich Sanity.',
    ],
    tip: 'Kaum sichtbar in der Jagd; Foto lässt es verschwinden → Phantom.',
  },
  {
    name: 'Poltergeist',
    evidence: ['spiritbox', 'uv', 'writing'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Wirft mehrere Gegenstände gleichzeitig und mit großer Wucht.',
    strength: 'Kann mit einem Wurf viele Objekte schleudern und so massiv Sanity ziehen.',
    weakness: 'In einem leeren Raum (keine Gegenstände) ist es nahezu machtlos.',
    behaviors: ['Wirft Dinge gehäuft und gleichzeitig.'],
    tip: 'Mehrere Objekte fliegen auf einmal → Poltergeist.',
  },
  {
    name: 'Banshee',
    evidence: ['uv', 'orbs', 'dots'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt nach der Sanity ihres Ziels (kann früh jagen)',
    ability: 'Wählt EIN Ziel und jagt nach dessen Sanity – egal wie es den anderen geht.',
    strength: 'Kann früh jagen, sobald ihr Ziel niedrige Sanity hat.',
    weakness: 'Konzentriert sich nur auf ihr Ziel; Kruzifix wirkt normal.',
    behaviors: [
      'Einzigartiger Gesang im Parabolmikrofon.',
      'Verfolgt gezielt eine einzelne Person.',
    ],
    tip: 'Gesang im Parabolmikro + jagt nur eine Person → Banshee.',
  },
  {
    name: 'Jinn',
    evidence: ['emf', 'uv', 'freezing'],
    speed: 'Normal; 2,5 m/s bei Sicht aus der Ferne (Strom AN)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Wird schnell, wenn es dich aus der Distanz sieht und der Strom AN ist.',
    strength: 'Kann mit Strom aus der Nähe sofort deine Sanity senken.',
    weakness: 'Kann den Sicherungskasten nicht ausschalten – Strom aus nimmt ihm das Tempo.',
    behaviors: ['Hält normalen Abstand, beschleunigt aber bei Sicht + Strom.'],
    tip: 'Schnell bei Strom an, normal wenn du die Sicherung ziehst → Jinn.',
  },
  {
    name: 'Mare',
    evidence: ['spiritbox', 'orbs', 'writing'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 60% im Dunkeln, erst ab 40% im Licht',
    ability: 'Jagt im Dunkeln deutlich früher; bevorzugt Dunkelheit.',
    strength: 'Kann Lichtschalter sofort wieder ausschalten.',
    weakness: 'Licht anlassen senkt die Jagd-Chance; kann Lichter nicht selbst einschalten.',
    behaviors: ['Schaltet ständig Lichter aus.'],
    tip: 'Dreht Licht aus und jagt im Dunkeln früh → Mare.',
  },
  {
    name: 'Revenant',
    evidence: ['orbs', 'writing', 'freezing'],
    speed: 'Sehr langsam (1,0) ohne Sicht, sehr schnell (3,0) bei Sicht',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Bei Sicht auf einen Spieler wird es extrem schnell (3,0 m/s).',
    strength: 'Tödlich schnell, sobald es dich sieht.',
    weakness: 'Ohne Sicht kriecht es sehr langsam (1,0) – Verstecken ist sehr wirksam.',
    behaviors: ['Langsames Umherwandern, schlagartige Beschleunigung bei Sicht.'],
    tip: 'Verstecken: kommt langsam; sieht es dich: rasend schnell → Revenant.',
  },
  {
    name: 'Shade',
    evidence: ['emf', 'writing', 'freezing'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Sehr scheu – jagt erst ab 35% Sanity',
    ability: 'Extrem schüchtern; sehr schwer zu provozieren.',
    strength: 'Wenig Aktivität/Beweise, je mehr Leute in der Nähe sind.',
    weakness: 'Jagt nicht, wenn ein Spieler im selben Raum ist – zusammenbleiben schützt.',
    behaviors: [
      'Auffällig wenig Aktivität, besonders in der Gruppe.',
      'Kein Geisterereignis, wenn jemand im Raum steht.',
    ],
    tip: 'Kaum Aktivität, jagt extrem spät → Shade.',
  },
  {
    name: 'Demon',
    evidence: ['uv', 'writing', 'freezing'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt schon ab 70% – früh und häufig',
    ability: 'Kann sehr früh und mit kurzer Abklingzeit jagen (aggressivster Geist).',
    strength: 'Initiiert Jagden öfter als jeder andere Geist.',
    weakness: 'Kruzifix wirkt auf größere Reichweite; erfolgreiche Ouija-Fragen ziehen weniger Sanity.',
    behaviors: ['Jagt früh und oft, auch bei hoher Sanity.'],
    tip: 'Ungewöhnlich frühe/häufige Jagden → Demon. Kruzifix bereithalten.',
  },
  {
    name: 'Yurei',
    evidence: ['orbs', 'freezing', 'dots'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Geisterereignisse senken die Sanity stärker als üblich.',
    strength: 'Kann mit einem Ereignis viel Sanity auf einmal ziehen.',
    weakness: 'Smudge im Geisterraum sperrt es dort ~60 s ein (kann nicht raus).',
    behaviors: ['Schließt manchmal Türen.', 'Großer Sanity-Verlust durch Ereignisse.'],
    tip: 'Plötzlich großer Sanity-Sprung nach unten → Yurei.',
  },
  {
    name: 'Oni',
    evidence: ['emf', 'freezing', 'dots'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Sehr aktiv und in Jagden stärker sichtbar; mehr Sanity-Drain bei Ereignissen.',
    strength: 'Mehr Aktivität, besonders wenn Spieler in der Nähe sind.',
    weakness: 'Die hohe Aktivität verrät es schnell; macht keine „Geisterball"-Ereignisse (Luft-Events).',
    behaviors: ['Extrem hohe Aktivität.', 'Während der Jagd auffällig gut sichtbar.'],
    tip: 'Sehr viel Aktivität + gut sichtbar in der Jagd → Oni.',
  },
  {
    name: 'Yokai',
    evidence: ['spiritbox', 'orbs', 'dots'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Reden in der Nähe hebt die Schwelle auf 80%',
    ability: 'Sprechen in seiner Nähe provoziert Jagden (jagt schon bei höherer Sanity).',
    strength: 'Kann durch Stimmen sehr früh zur Jagd gereizt werden.',
    weakness: 'Während der Jagd hört es nur Spieler in unmittelbarer Nähe – aus der Ferne reden ist sicher.',
    behaviors: ['Reagiert stark auf Stimmen in der Nähe.'],
    tip: 'Jagt früh bei Reden in der Nähe; hört dich in der Jagd nur aus der Nähe → Yokai.',
  },
  {
    name: 'Hantu',
    evidence: ['uv', 'orbs', 'freezing'],
    speed: 'Schneller in Kälte (bis 2,7), langsamer in warmen Räumen (~1,4)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Bewegt sich umso schneller, je kälter der Raum ist.',
    strength: 'In Gefrierräumen extrem schnell.',
    weakness: 'Schaltet den Strom nie ein; bei Strom an / wärmeren Räumen deutlich langsamer; sichtbarer Atem in der Jagd.',
    behaviors: ['Bevorzugt Kälte; lässt den Sicherungskasten aus.'],
    tip: 'Schnell in der Kälte, langsam wenn warm/Strom an → Hantu.',
  },
  {
    name: 'Goryo',
    evidence: ['emf', 'uv', 'dots'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Zeigt D.O.T.S. nur über die Videokamera, nicht mit bloßem Auge.',
    strength: 'D.O.T.S.-Beweis ist live kaum zu sehen und leicht zu übersehen.',
    weakness: 'Verlässt seinen Lieblingsraum selten; entfernt sich kaum von Spielern.',
    behaviors: ['D.O.T.S. nur auf dem Kamerabildschirm sichtbar.', 'Bleibt fast immer im selben Raum.'],
    tip: 'Kamera auf DOTS richten – nur dort sichtbar → Goryo.',
  },
  {
    name: 'Myling',
    evidence: ['emf', 'uv', 'writing'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Sehr leise während der Jagd (kaum Schritt-/Jagdgeräusche).',
    strength: 'In der Jagd schwer zu hören → schwerer auszuweichen.',
    weakness: 'Erzeugt mehr paranormale Geräusche im Parabolmikrofon und „spricht" häufiger.',
    behaviors: ['Leise Schritte in der Jagd, aber viele Mikro-Geräusche.'],
    tip: 'Leise Jagd, aber viel Aktivität am Parabolmikro → Myling.',
  },
  {
    name: 'Onryo',
    evidence: ['spiritbox', 'orbs', 'freezing'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Behandelt Flammen wie Kruzifixe; jede 3. erloschene Flamme kann Jagd auslösen',
    ability: 'Eine ausgehende Flamme kann (jede 3.) eine Jagd auslösen.',
    strength: 'Kann durch ausgehende Kerzen Jagden „erzwingen".',
    weakness: 'Brennende Flammen in der Nähe verhindern Jagden komplett.',
    behaviors: ['Bläst Flammen/Kerzen aus.', 'Jagt oft direkt nach dem Erlöschen einer Flamme.'],
    tip: 'Kerzen aufstellen: geht eine aus und es jagt sofort → Onryo.',
  },
  {
    name: 'The Twins',
    evidence: ['emf', 'spiritbox', 'freezing'],
    speed: 'Ein Zwilling langsam (1,5), einer schnell (1,9)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Zwei „Zwillinge", die getrennt interagieren und beide jagen können.',
    strength: 'Interaktionen an zwei entfernten Orten; einer jagt schnell, einer langsam.',
    weakness: 'Die beiden interagieren oft fast gleichzeitig an verschiedenen Stellen – leicht erkennbar.',
    behaviors: ['Zwei Interaktionsquellen, oft weit auseinander.'],
    tip: 'Zwei Interaktionen kurz nacheinander an verschiedenen Orten → The Twins.',
  },
  {
    name: 'Raiju',
    evidence: ['emf', 'orbs', 'dots'],
    speed: 'Normal; 2,5 m/s nahe aktiver Elektronik',
    hunt: 'Jagt ab 65% nahe aktiver Elektronik',
    ability: 'Wird schnell in der Nähe eingeschalteter Geräte und stört Technik aus größerer Distanz.',
    strength: 'Mit Ausrüstung in der Nähe sehr schnell und jagt früher.',
    weakness: 'Verrät seine Position durch starke Elektronik-Störungen; ohne Technik normal/langsam.',
    behaviors: ['Entlädt/stört Ausrüstung stark und aus der Ferne.'],
    tip: 'Beschleunigt nahe deiner Geräte, starke Störungen → Raiju.',
  },
  {
    name: 'Obake',
    evidence: ['emf', 'uv', 'orbs'],
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Kann Fingerabdrücke verändern oder ganz darauf verzichten; selten 6-Finger-Abdruck.',
    strength: 'UV-Spuren verschwinden schneller als bei anderen → Beweis leicht zu verpassen.',
    weakness: 'Mutiert kurz während der Jagd (Modellwechsel, auf Foto erkennbar); 6-Finger-Abdruck ist eindeutig.',
    behaviors: ['Manchmal 6-Finger-Handabdruck.', 'UV-Beweise verschwinden schnell oder fehlen ganz.'],
    tip: '6-Finger-Abdruck oder verschwindende Fingerabdrücke → Obake.',
  },
  {
    name: 'The Mimic',
    evidence: ['spiritbox', 'uv', 'freezing'],
    orbsAlways: true,
    speed: 'Normal (1,7 m/s)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Ahmt die Fähigkeiten/das Verhalten anderer Geister nach (wechselt regelmäßig).',
    strength: 'Verhält sich wie ein zufälliger anderer Geist – verwirrend zu identifizieren.',
    weakness: 'Zeigt zusätzlich IMMER Geisterkugeln als 4. (Fake-)Beweis – das verrät es.',
    behaviors: ['Verhalten wechselt, „kopiert" andere Geister.', 'Kugeln zusätzlich zu den 3 echten Beweisen.'],
    tip: 'Geisterkugeln zusätzlich zu Box/UV/Kälte → The Mimic.',
  },
  {
    name: 'Moroi',
    evidence: ['spiritbox', 'writing', 'freezing'],
    speed: 'Schneller je niedriger DEINE Sanity (bis ~2,25)',
    hunt: 'Jagt ab 50% Sanity',
    ability: '„Verflucht" über Spirit-Box-Antworten → schnellerer Sanity-Verlust.',
    strength: 'Bei niedriger Sanity extrem schnell und gefährlich.',
    weakness: 'Bei hoher Sanity normal/langsam; Smudge blendet es länger; Sanity hochhalten kontert es.',
    behaviors: ['Spirit-Box-Antworten beschleunigen deinen Sanity-Verlust.'],
    tip: 'Wird mit sinkender Sanity immer schneller → Moroi. Sanity hochhalten.',
  },
  {
    name: 'Deogen',
    evidence: ['spiritbox', 'writing', 'dots'],
    speed: 'Sehr schnell aus der Ferne (~3,0), sehr langsam aus der Nähe (~0,4)',
    hunt: 'Jagt ab 40% Sanity',
    ability: 'Spürt Spieler immer auf – kann dich nie „verlieren".',
    strength: 'Sehr schnell aus der Distanz; findet dich überall.',
    weakness: 'Aus nächster Nähe kriecht es extrem langsam – um Objekte loopen funktioniert gut.',
    behaviors: ['Schweres Atmen in der Spirit Box aus der Nähe.', 'Steuert in der Jagd immer direkt auf dich zu.'],
    tip: 'Rast heran, wird dann ganz langsam an dir → Deogen.',
  },
  {
    name: 'Thaye',
    evidence: ['orbs', 'writing', 'dots'],
    speed: 'Anfangs schnell (~2,75), wird mit der Zeit langsamer (bis 1,0)',
    hunt: 'Schwelle anfangs ~75%, sinkt mit dem Altern',
    ability: 'Altert mit der Zeit (wenn Spieler nahe sind) – Tempo & Jagd-Schwelle sinken.',
    strength: 'Jung sehr gefährlich: schnell und jagt früh.',
    weakness: 'Mit dem Altern langsam, passiver und jagt erst spät – Zeit spielt für dich.',
    behaviors: ['Anfangs sehr aktiv/schnell, lässt mit der Zeit stark nach.'],
    tip: 'Hohe Aktivität am Anfang, deutliche Abnahme über die Zeit → Thaye.',
  },
  {
    name: 'Obambo',
    evidence: ['writing', 'uv', 'dots'],
    speed: 'Variabel je nach Zustand (ruhig langsamer / aggressiv schneller)',
    hunt: 'Aggressiv: jagt früher; ruhig: jagt später',
    ability: 'Wechselt etwa alle 2 Minuten zwischen ruhigem und aggressivem Zustand.',
    strength: 'Im aggressiven Zustand schnell und jagt früh; aggressive Jagden sind kürzer (–20 %), aber heftig.',
    weakness: 'Im ruhigen Zustand langsam und jagt spät – günstiges Timing abwarten.',
    behaviors: ['Aktivität & Tempo schwanken im ~2-Minuten-Takt.'],
    tip: 'Aktivität/Tempo schwankt rhythmisch (ruhig ↔ aggressiv) → Obambo.',
  },
  {
    name: 'Gallu',
    evidence: ['emf', 'uv', 'spiritbox'],
    speed: 'Zustandsabhängig: Normal 1,7 · Wütend 1,96 · Geschwächt 1,36 m/s',
    hunt: 'Wütend: jagt früher (~60 %); Geschwächt: jagt später (~40 %)',
    ability: 'Durchläuft 3 Zustände (Normal → Wütend → Geschwächt), die Tempo, Jagd-Schwelle, Kruzifix-Reichweite und Räucher-Blindheit ändern.',
    strength: 'Im wütenden Zustand schnell und jagt früh; Kruzifix wirkt dann auf kürzere Reichweite.',
    weakness: 'Salz, Räucherwerk oder Kruzifix schalten den Zustand um; im geschwächten Zustand langsam und jagt spät.',
    behaviors: ['Tempo/Verhalten ändert sich in „Wellen" (Zuständen).', 'Geht nach Salz/Räucherwerk/Kruzifix in einen anderen Zustand.'],
    tip: 'Verhalten/Tempo wechselt deutlich in Zuständen → Gallu.',
  },
  {
    name: 'Dayan',
    evidence: ['emf', 'orbs', 'spiritbox'],
    speed: 'Normal (1,7); in 10 m Nähe abhängig von deiner Bewegung',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Innerhalb von 10 m richtet sich ihr Tempo danach, ob/wie du dich bewegst.',
    strength: 'Bewegst du dich in ihrer Nähe, wird sie schneller; angesammeltes Sicht-Tempo schlägt voll durch, sobald sie die 10 m verlässt.',
    weakness: 'Stehst du in der Nähe still, bewegt sie sich langsamer.',
    behaviors: ['Ab 10 m normaler Sicht-Speed; in 10 m Nähe bewegungsabhängig.'],
    tip: 'In der Nähe still stehen bleiben macht sie langsam → Dayan.',
  },
  {
    name: 'Kormos',
    evidence: ['orbs', 'spiritbox', 'uv'],
    speed: '1,7 m/s; bis ~2,21, wenn es dich „hört" (Pseudo-Sicht)',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Ist blind – ortet dich nur über Geräusche & Elektronik (Schleichen ~10 m, Gehen ~15 m, Sprinten ~30 m).',
    strength: 'Beschleunigt, sobald es deine Schritte hört (Pseudo-Sicht bis ~2,21 m/s).',
    weakness: 'Stehst du während der Jagd völlig still und lautlos, kann es dich nicht finden (es sieht nichts).',
    behaviors: ['Reagiert stark auf Schritte/Stimme/Elektronik statt auf Sicht.'],
    tip: 'In der Jagd still & lautlos stehen → der Kormos verliert dich.',
  },
  {
    name: 'Aswang',
    evidence: ['freezing', 'writing', 'dots'],
    speed: 'Etwas langsamer (1,53 m/s); beschleunigt bei Sicht schneller als üblich',
    hunt: 'Jagt ab 50% Sanity',
    ability: 'Erreicht sein Sicht-Tempo schneller als andere Geister.',
    strength: 'Baut bei Sichtkontakt zügig Geschwindigkeit auf.',
    weakness: 'Erreichst du während einer Jagd ein echtes Versteck (Schrank/Spind), endet die Jagd sofort.',
    behaviors: ['Grundtempo leicht unter dem Standard, aber schnelle Sicht-Beschleunigung.'],
    tip: 'Jagd endet sofort, sobald du in einen Schrank/Spind gehst → Aswang.',
  },
];
